post_install() {
  _mkuser
  chown -R ob:ob /srv/blockchain /usr/share/obelisk /var/log/obelisk
}

post_install() {
  post_install
}

post_remove() {
  _rmuser
}

_mkuser() {
  getent passwd ob &>/dev/null || {
    echo -n "Creating ob user... "
    grep -E "^ob:" /etc/group >/dev/null || groupadd ob
    useradd -m -d /etc/obelisk -g ob -s /bin/false ob
    echo "done"
  }
}

_rmuser() {
  echo -n "Removing ob user... "
  userdel -rf ob 2>/dev/null
  echo "done"
}
